### ISSUE TITLE
Get all unit tests passing for ES 2.4 and ES 5.6

### ISSUE THREAD

**Issue by TwP** [github/elastomer-client#157]
Now that we have a [CI environment](https://github.com/github/elastomer-client/issues/142) configured for Elasticsearch 5.6, we need to get all the unit tests passing for both ES 2.4 and ES 5.6. The end goal is that the `elastomer-client` gem be compatible with both versions while breaking as little backwards compatibility as possible.

After we have green tests we can proceed to pull in new features from ES 5.X into the gem.

## Things To Fix

- [x] Warmers aren't a thing anymore in 5.x @look #161
- [x] `:payloads` at index-time are not support @juruen #155
- [x] Scan/scroll changes @juruen #163
- [x] Index mappings: `string` type becomes `text` for analyzed string fields, `keyword` for non-analyzed (1st to come up is `title` but there will be lots) @look #166
- [x] `filtered` query deprecation (replaced with `bool` queries) @look #169 
- [x] misc field naming convention changes in mappings (`.percolator`) @elireisman #167
- [x] analyzer needs to be passed as a json object in the body (in `Index#analyze` from `Elastomer::Client::Index#test_0009_analyzes text and returns tokens`) @juruen #168
- [x] Suggest `output` removed (`output` in `Elastomer::Client::Index::when an index exists#test_0014_performs suggestion queries`) @look #173
- [x] Expected param change (`consistency` in `Elastomer::Client::Docs#test_0004_extracts underscore attributes from the document`) @look #178
- [x] seeing some errors using `client` accessor in Warmer tests now, probably just need to use test-global `$client` here? @elireisman #172
- [x] Exceptions aren't raised the same way (`[Elastomer::Client::QueryParsingError] exception expected, not Class: <Elastomer::Client::RequestError>`) @look #175

**Comment by elireisman** [comment]
Ah sorry, I just made an issue to track individual bits of this work (looks like @juruen is pushing one of the items soon already!) but I can close as dupe and more that checklist here if you like @TwP

**Comment by TwP** [comment]
@elireisman great minds think alike! Yes, lets use this issue here for the unit test work. I've opened a few others related to the ES 5.X upgrade. Thank you :bowing_man:

**Comment by elireisman** [comment]
No problem, thanks, should have used this anyway! Copied from that issue:

 I ran the test suite against a localk ES 5.6 docker image and I get 69 fails that we can bucket into these fixes so far (WIP, I'll be updating and refining this list as we go):

- [ ] Warmers aren't a thing anymore in 5.x
- [ ] Scan/scroll changes
- [ ] Index mappings: `string` type becomes `text` for analyzed string fields, `keyword` for non-analyzed (1st to come up is `title` but there will be lots)
- [ ] Strict boolean field values
- [ ] misc field naming convention changes in mappings (`.percolator`, `_type`)
- [x] Index mappings: invalid params (`suggest`'s `payload` param came up 1st but there will be more)

**Comment by juruen** [comment]
Hey, I started to look at `scan/scroll changes`  in https://github.com/github/elastomer-client/pull/163 If at some point you guys have time to provide some feedback, it'd be awesome!

**Comment by TwP** [comment]
I've taken the list of work from Eli's comment and moved it up into the issue body itself. To coordinate on work lets follow this plan:

* add new things to fix as a todo item up in the main issue body
* add your name to an item in the list when you start working on it
* add a PR number to the todo items when you have a PR going
* only mark the todo as complete when the PR is merged

As you find new failures and what not, please add them to the todo list in the main issue body. Anyone should be able to edit the main issue body, and if you can't please let me know.

**Comment by look** [comment]
I'm going to close this issue because the tests are now passing on ES 5. We can reopen if new problems are discovered.
