### ISSUE TITLE
Incorporate new ES 5.X features

### ISSUE THREAD

**Issue by TwP** [github/elastomer-client#158]
We need to pull in new features from ES 5.X that are not yet supported by the gem. When the gem is used with an ES 2.X cluster, a sensible empty result should be returned from these methods.

- [x] Delete by query [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-delete-by-query.html) @look #185
- [x] Task management API [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/tasks.html) @elireisman #187 
- [x] Raise `IllegalArgument` exceptions when returned from Elasticsearch #184 
- [x] Upgrades tp + github/github deployment(s) of `elastomer-client` to pull in `VersionSupport` shims for ES2~ES5 transition period @elireisman @look (multiple patches)
- [x] Pattern for parameter validation @twp [here](https://github.com/github/elastomer-client/pull/198)

**Comment by elireisman** [comment]
With the release of `elastomer-client` v3.1.x I think we're all done here, including param validation - closing this
